---
galaxy_info:
  author: "Barry Britt <bbritt@iastate.edu>"
  description: Installs and Configures apache2 for RHEL
  company: "Iowa State Univeristy"
  license: GPLv2
  min_ansible_version: 1.0
  platforms:
    - name: EL
      versions:
        - 7
  categories:
    - web
