---
- name: Create apache vhost
  template:
    src: vhosts.j2
    dest: "{{ apache_sites_available_path }}/{{ item.ServerName }}.{{ item.Port }}.conf"
    owner: root
    mode: 0644
  with_items: "{{apache_vhosts}}"
  notify: Restart apache

- name: Enable vhosts
  command: /etc/httpd/bin/a2ensite {{ item.ServerName }}.{{ item.Port }}.conf
  with_items: "{{apache_vhosts}}"
  ignore_errors: yes
  register: echo
  notify: Restart apache

- name: Create vhost directories
  file:
    path: "{{ item.DocumentRoot }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items: "{{apache_vhosts}}"
