
- name: Configure touchterrain
  hosts: touchterrain.example.org
  user: root
  connection: smart

  vars_prompt:
    name: "touchterrain_host"
    prompt: 'Please enter apache vhost hostname'
    default: 'touchterrain.example.org'
    private: no

  vars:
    touchterrain_dir: '/var/www/html/touchterrain'
    touchterrain_user: 'apache'
    touchterrain_group: 'apache'

    apache_enable_vhosts: true
    apache_vhosts_enabled:
      - "{{touchterrain_host}}.80"
    apache_vhosts:
      - ServerName: "{{touchterrain_host}}"
        Port: "80"
        ServerAdmin: root@localhost
        WSGIScriptAlias: "/ {{touchterrain_dir}}/server/touchterrain.wsgi"
        DocumentRoot: "{{touchterrain_dir}}"
        ErrorLog: "/var/log/httpd/{{touchterrain_host}}-error.log"
        DirectoryIndex: 'index.html'
        KeepAliveTimeout: "162000"
        Alias:
          - "/tmp  {{touchterrain_dir}}/server/tmp"
          - "/docs  {{touchterrain_dir}}/docs"
        Directory:
        - path: "{{touchterrain_dir}}/server/tmp"
          Options: '-Indexes'
          Require:
            - scope: all
              value: granted
        - path: "{{touchterrain_dir}}/docs"
          Options: '-Indexes'
          Require:
            - scope: all
              value: granted
        - path: "{{touchterrain_dir}}"
          Options: -Indexes
    configure_firewalld: true
    firewalld_default_zone: public
    firewalld_service_rules:
      - service: http
        zone: public
        state: enabled


  pre_tasks:
    - name: Create group of user to run wsgi process
      group:
        name: "{{touchterrain_group}}"
        state: present
    - name: Create user to run wsgi process
      user:
        name: "{{touchterrain_user}}"
        comment: "TouchTerrain"
        group: "{{touchterrain_group}}"


  roles:
    - apache
    - ISU-Ansible.firewall

  tasks:
    - name: Install a few packages
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - python
        - numpy
        - python-pillow
        - python-pip
        - git
        - mod_wsgi
    - name: Download Google App Engine SDK
      get_url:
        url: https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.40.zip
        dest: /root/google_appengine.zip
    - name: Unzip Google App Engine SDK
      shell: unzip -o /root/google_appengine.zip -d /usr/local/bin
    - name: Install GEE requirements with PIP
      pip:
        name: "{{ item }}"
      with_items:
        - pyCrypto
        - google-api-python-client
        - pyOpenSSL
        - earthengine-api
        - webapp2
        - WebOb
        - Paste #might not this if apache handles wsgi for us instead
        - vectors
    - name: Create application directory
      file:
        path: "{{touchterrain_dir}}"
        owner: "{{touchterrain_user}}"
        group: "{{touchterrain_group}}"
        mode: u=r,g=r,o=r
        state: directory
        recurse: yes
        setype: httpd_sys_content_t
    - name: Create key directory
      file:
        path: /var/www/tt_key
        owner: root
        group: root
        mode: u=rx,g=rx,o=rx
        state: directory
        recurse: yes
        setype: httpd_sys_content_t
    - name: Deleting the folder b/c force flag in ansible 2.2 is currently broken - https://github.com/ansible/ansible-modules-core/issues/5504
      shell: rm -rf "{{touchterrain_dir}}"
    - name: Pulling the git repo
      git:
        repo: https://github.com/ChHarding/TouchTerrain_for_CAGEO.git
        dest: "{{touchterrain_dir}}"
        force: yes
        version: v1.19
    - name: Update the conf to use correct google analytics account
      replace:
        dest="{{touchterrain_dir}}/server/index.html"
        regexp='.*UA-XXXXXXXX.*'
        replace="'UA-YOURID',"
    - name: Update the conf to use correct EE_ACCOUNT
      lineinfile: dest="{{touchterrain_dir}}/server/config.py" regexp=^EE_ACCOUNT line="EE_ACCOUNT = 'youreeaccount'"
    - name: Update the conf to use correct private key path
      lineinfile: dest="{{touchterrain_dir}}/server/config.py" regexp=^EE_PRIVATE_KEY_FILE line="EE_PRIVATE_KEY_FILE = '/var/www/tt_key/privatekey.pem'"
    - name: Copy the earth engine key to the server
      copy:
        src: "{{filedir}}/touchterrain/privatekey.pem"
        dest: /var/www/tt_key/privatekey.pem
    - name: Set permissions on /var/www/html/touchterrain
      file:
        path: "{{touchterrain_dir}}"
        owner: "{{touchterrain_user}}"
        group: "{{touchterrain_group}}"
        mode: u=rx,g=r,o=rx
        state: directory
        recurse: yes
        setype: httpd_sys_content_t
    - name: Set directory permissions under /var/www/html
      command: /usr/bin/find /var/www/html -type d -exec /usr/bin/chmod u+rx {} \;
    - name: Set permissions for touchterrain /tmp
      file:
        path: "{{touchterrain_dir}}/server/tmp"
        mode: u+rwx,o+rx
        state: directory
        recurse: yes
        setype: httpd_sys_rw_content_t
    - name: Permanently set SE Linux context for tmp dir
      sefcontext:
          target: "{{touchterrain_dir}}/server/tmp"
          setype: httpd_sys_rw_content_t
          state: present
      ignore_errors: true
    - name: Set permissions for TouchTerrain_app
      sefcontext:
        target: "{{touchterrain_dir}}/server/TouchTerrain_app.py"
        setype: httpd_sys_script_exec_t
        state: present
      ignore_errors: true
    - name: Restart httpd
      service:
        name: httpd
        enabled: yes
        state: restarted
